export const LOGIN_REQUEST = "USER_REQUEST";
export const LOGIN_FAIL = "USER_FAIL";
export const LOGIN_SUCCESS = "USER_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = " REGISTER_USER_SUCCESS";
